# Generated by Django 4.0.6 on 2022-07-10 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('upc', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11, '10 digit UPC must have leading 0')])),
                ('name', models.CharField(max_length=50)),
                ('case_qty', models.IntegerField()),
                ('case_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('member_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qoh', models.IntegerField()),
            ],
        ),
    ]
