# Generated by Django 4.0.6 on 2022-07-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='qoh',
        ),
        migrations.AddField(
            model_name='item',
            name='department',
            field=models.CharField(choices=[('DAI', 'Dairy'), ('FRO', 'Frozen'), ('GRO', 'Grocery')], default='DAI', max_length=3),
        ),
    ]
