# Generated by Django 4.0.6 on 2022-07-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_qoh_item_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qoh',
            field=models.IntegerField(default=0),
        ),
    ]
